# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DataShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataShow(object):
    def setupUi(self, DataShow):
        DataShow.setObjectName("DataShow")
        DataShow.resize(1331, 912)
        DataShow.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"CustimTableView {\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #D8E6F2;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(DataShow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = CustomTableView(DataShow)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.first_page_btn = QtWidgets.QPushButton(DataShow)
        self.first_page_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.first_page_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.first_page_btn.setStyleSheet("")
        self.first_page_btn.setObjectName("first_page_btn")
        self.horizontalLayout.addWidget(self.first_page_btn)
        self.pre_page_btn = QtWidgets.QPushButton(DataShow)
        self.pre_page_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.pre_page_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pre_page_btn.setStyleSheet("")
        self.pre_page_btn.setObjectName("pre_page_btn")
        self.horizontalLayout.addWidget(self.pre_page_btn)
        self.page_entry = QtWidgets.QLineEdit(DataShow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_entry.sizePolicy().hasHeightForWidth())
        self.page_entry.setSizePolicy(sizePolicy)
        self.page_entry.setMinimumSize(QtCore.QSize(50, 0))
        self.page_entry.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.page_entry.setFont(font)
        self.page_entry.setStyleSheet("")
        self.page_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.page_entry.setObjectName("page_entry")
        self.horizontalLayout.addWidget(self.page_entry)
        self.next_page_btn = QtWidgets.QPushButton(DataShow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_page_btn.sizePolicy().hasHeightForWidth())
        self.next_page_btn.setSizePolicy(sizePolicy)
        self.next_page_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.next_page_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.next_page_btn.setStyleSheet("")
        self.next_page_btn.setObjectName("next_page_btn")
        self.horizontalLayout.addWidget(self.next_page_btn)
        self.last_page_btn = QtWidgets.QPushButton(DataShow)
        self.last_page_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.last_page_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.last_page_btn.setStyleSheet("")
        self.last_page_btn.setObjectName("last_page_btn")
        self.horizontalLayout.addWidget(self.last_page_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(DataShow)
        QtCore.QMetaObject.connectSlotsByName(DataShow)

    def retranslateUi(self, DataShow):
        _translate = QtCore.QCoreApplication.translate
        DataShow.setWindowTitle(_translate("DataShow", "Form"))
        self.first_page_btn.setText(_translate("DataShow", "<<"))
        self.pre_page_btn.setText(_translate("DataShow", "<"))
        self.next_page_btn.setText(_translate("DataShow", ">"))
        self.last_page_btn.setText(_translate("DataShow", ">>"))
from CustomTableView import CustomTableView
